<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="1" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="74" started-at="2018-08-05T05:32:01Z" finished-at="2018-08-05T05:32:01Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="74" started-at="2018-08-05T05:32:01Z" finished-at="2018-08-05T05:32:01Z">
      <class name="TestNG.PrintAExample">
        <test-method status="PASS" signature="addA()[pri:-1, instance:TestNG.PrintAExample@74ad1f1f]" name="addA" duration-ms="15" started-at="2018-08-05T05:32:01Z" finished-at="2018-08-05T05:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addA -->
        <test-method status="PASS" signature="editA()[pri:2, instance:TestNG.PrintAExample@74ad1f1f]" name="editA" duration-ms="0" started-at="2018-08-05T05:32:01Z" finished-at="2018-08-05T05:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editA -->
        <test-method status="PASS" signature="editA()[pri:2, instance:TestNG.PrintAExample@74ad1f1f]" name="editA" duration-ms="0" started-at="2018-08-05T05:32:01Z" finished-at="2018-08-05T05:32:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editA -->
        <test-method status="FAIL" signature="failA()[pri:4, instance:TestNG.PrintAExample@74ad1f1f]" name="failA" duration-ms="0" started-at="2018-08-05T05:32:01Z" finished-at="2018-08-05T05:32:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at TestNG.PrintAExample.failA(PrintAExample.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failA -->
        <test-method status="SKIP" signature="dependA()[pri:5, instance:TestNG.PrintAExample@74ad1f1f]" name="dependA" duration-ms="0" started-at="2018-08-05T05:32:01Z" depends-on-methods="TestNG.PrintAExample.failA" finished-at="2018-08-05T05:32:01Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method PrintAExample.dependA()[pri:5, instance:TestNG.PrintAExample@74ad1f1f] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method PrintAExample.dependA()[pri:5, instance:TestNG.PrintAExample@74ad1f1f] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dependA -->
      </class> <!-- TestNG.PrintAExample -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
